# Generated by Django 5.2.16 on 2026-07-30 23:56

import api.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_email', models.EmailField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.JSONField(default=dict)),
                ('resume_texte', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'analyses_ia',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationMistral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False)),
                ('api_key', api.fields.EncryptedTextField(blank=True, default='')),
                ('modele', models.CharField(default='mistral-large-latest', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuration_mistral',
            },
        ),
        migrations.CreateModel(
            name='GenerationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prompt_utilise', models.TextField(blank=True, default='')),
                ('modele', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_demande', models.PositiveIntegerField(default=0)),
                ('nombre_genere', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('erreur_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'generations_ia',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_email', models.EmailField(max_length=255)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('themes_filtres', models.CharField(blank=True, default='', help_text="CSV d'IDs de Theme, vide = tous", max_length=200)),
                ('difficulte_filtree', models.CharField(blank=True, default='', max_length=20)),
                ('nombre_questions', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Nombre de bonnes réponses', null=True)),
            ],
            options={
                'db_table': 'quiz_sessions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SiteExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('statut', models.CharField(choices=[('gratuit', 'Gratuit'), ('freemium', 'Freemium'), ('payant', 'Payant')], max_length=20)),
                ('offre_resume', models.TextField(blank=True, default='')),
                ('date_verification', models.DateField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sites_externes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('type', models.CharField(choices=[('qcm_unique', 'QCM à réponse unique'), ('qcm_multiple', 'QCM à réponses multiples'), ('vrai_faux', 'Vrai / Faux')], max_length=20)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('illustration_path', models.CharField(blank=True, default='', max_length=500)),
                ('illustration_credit', models.CharField(blank=True, default='', max_length=300)),
                ('explication_generale', models.TextField(blank=True, default='')),
                ('origine', models.CharField(choices=[('humaine', 'Humaine'), ('ia', 'IA')], default='humaine', max_length=10)),
                ('statut', models.CharField(choices=[('validee', 'Validée'), ('proposee', 'Proposée'), ('rejetee', 'Rejetée')], default='validee', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='api.generationia')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.theme')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('correcte', models.BooleanField(default=False)),
                ('explication', models.TextField(blank=True, default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='api.question')),
            ],
            options={
                'db_table': 'reponses',
            },
        ),
        migrations.AddField(
            model_name='generationia',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='api.theme'),
        ),
        migrations.CreateModel(
            name='FicheCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(help_text='Markdown')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('illustration_path', models.CharField(blank=True, default='', max_length=500)),
                ('illustration_credit', models.CharField(blank=True, default='', max_length=300)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='api.theme')),
            ],
            options={
                'db_table': 'fiches_cours',
                'ordering': ['theme__ordre', 'ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='QuizReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponses_choisies', models.JSONField(default=list, help_text='IDs de Reponse choisis')),
                ('correcte', models.BooleanField(default=False)),
                ('temps_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_donnees', to='api.quizsession')),
            ],
            options={
                'db_table': 'quiz_reponses',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
