# Generated by Django 5.2.16 on 2026-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seed_questions_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationia',
            name='deepsearch',
            field=models.BooleanField(default=False, help_text='Vérification factuelle par recherche web (connecteur Mistral web_search) avant génération.'),
        ),
    ]
