version: "3.9"

networks:
  sso-net:
    external: true
    name: sso-lab_sso-net
  dev-net:
    external: true
    name: dev-net

services:

  backend:
    build: ./backend
    container_name: code-route-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8096:8000"
    networks:
      - sso-net
      - dev-net
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/code-route-api/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 8000}}"

  frontend:
    build: ./frontend
    container_name: code-route-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "4200:80"
    networks:
      - sso-net
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/code-route/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
